// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/xtlm_ipc_axis.proto

#ifndef PROTOBUF_INCLUDED_proto_2fxtlm_5fipc_5faxis_2eproto
#define PROTOBUF_INCLUDED_proto_2fxtlm_5fipc_5faxis_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fxtlm_5fipc_5faxis_2eproto


#ifdef CADENCE
#define X_GOOGLE_NAMESPACE google37
#else
#define X_GOOGLE_NAMESPACE google
#endif

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fxtlm_5fipc_5faxis_2eproto {
  static const ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::X_GOOGLE_NAMESPACE::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::X_GOOGLE_NAMESPACE::protobuf::internal::FieldMetadata field_metadata[];
  static const ::X_GOOGLE_NAMESPACE::protobuf::internal::SerializationTable serialization_table[];
  static const ::X_GOOGLE_NAMESPACE::protobuf::uint32 offsets[];
};
void AddDescriptors_proto_2fxtlm_5fipc_5faxis_2eproto();
namespace xtlm_ipc {
class axi_stream_frame;
class axi_stream_frameDefaultTypeInternal;
extern axi_stream_frameDefaultTypeInternal _axi_stream_frame_default_instance_;
class axi_stream_frames;
class axi_stream_framesDefaultTypeInternal;
extern axi_stream_framesDefaultTypeInternal _axi_stream_frames_default_instance_;
class axi_stream_packet;
class axi_stream_packetDefaultTypeInternal;
extern axi_stream_packetDefaultTypeInternal _axi_stream_packet_default_instance_;
class axi_stream_resp;
class axi_stream_respDefaultTypeInternal;
extern axi_stream_respDefaultTypeInternal _axi_stream_resp_default_instance_;
class axi_stream_responses;
class axi_stream_responsesDefaultTypeInternal;
extern axi_stream_responsesDefaultTypeInternal _axi_stream_responses_default_instance_;
class axi_stream_sample_req;
class axi_stream_sample_reqDefaultTypeInternal;
extern axi_stream_sample_reqDefaultTypeInternal _axi_stream_sample_req_default_instance_;
}  // namespace xtlm_ipc
namespace X_GOOGLE_NAMESPACE {
namespace protobuf {
template<> ::xtlm_ipc::axi_stream_frame* Arena::CreateMaybeMessage<::xtlm_ipc::axi_stream_frame>(Arena*);
template<> ::xtlm_ipc::axi_stream_frames* Arena::CreateMaybeMessage<::xtlm_ipc::axi_stream_frames>(Arena*);
template<> ::xtlm_ipc::axi_stream_packet* Arena::CreateMaybeMessage<::xtlm_ipc::axi_stream_packet>(Arena*);
template<> ::xtlm_ipc::axi_stream_resp* Arena::CreateMaybeMessage<::xtlm_ipc::axi_stream_resp>(Arena*);
template<> ::xtlm_ipc::axi_stream_responses* Arena::CreateMaybeMessage<::xtlm_ipc::axi_stream_responses>(Arena*);
template<> ::xtlm_ipc::axi_stream_sample_req* Arena::CreateMaybeMessage<::xtlm_ipc::axi_stream_sample_req>(Arena*);
}  // namespace protobuf
}  // namespace X_GOOGLE_NAMESPACE
namespace xtlm_ipc {

// ===================================================================

class axi_stream_packet :
    public ::X_GOOGLE_NAMESPACE::protobuf::Message /* @@protoc_insertion_point(class_definition:xtlm_ipc.axi_stream_packet) */ {
 public:
  axi_stream_packet();
  virtual ~axi_stream_packet();

  axi_stream_packet(const axi_stream_packet& from);

  inline axi_stream_packet& operator=(const axi_stream_packet& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  axi_stream_packet(axi_stream_packet&& from) noexcept
    : axi_stream_packet() {
    *this = ::std::move(from);
  }

  inline axi_stream_packet& operator=(axi_stream_packet&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::X_GOOGLE_NAMESPACE::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::X_GOOGLE_NAMESPACE::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::X_GOOGLE_NAMESPACE::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const axi_stream_packet& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const axi_stream_packet* internal_default_instance() {
    return reinterpret_cast<const axi_stream_packet*>(
               &_axi_stream_packet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(axi_stream_packet* other);
  friend void swap(axi_stream_packet& a, axi_stream_packet& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline axi_stream_packet* New() const final {
    return CreateMaybeMessage<axi_stream_packet>(nullptr);
  }

  axi_stream_packet* New(::X_GOOGLE_NAMESPACE::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<axi_stream_packet>(arena);
  }
  void CopyFrom(const ::X_GOOGLE_NAMESPACE::protobuf::Message& from) final;
  void MergeFrom(const ::X_GOOGLE_NAMESPACE::protobuf::Message& from) final;
  void CopyFrom(const axi_stream_packet& from);
  void MergeFrom(const axi_stream_packet& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseContext* ctx);
  ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::X_GOOGLE_NAMESPACE::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::X_GOOGLE_NAMESPACE::protobuf::io::CodedOutputStream* output) const final;
  ::X_GOOGLE_NAMESPACE::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::X_GOOGLE_NAMESPACE::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(axi_stream_packet* other);
  private:
  inline ::X_GOOGLE_NAMESPACE::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::X_GOOGLE_NAMESPACE::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes data = 1;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // optional bytes tuser = 4;
  bool has_tuser() const;
  void clear_tuser();
  static const int kTuserFieldNumber = 4;
  const ::std::string& tuser() const;
  void set_tuser(const ::std::string& value);
  #if LANG_CXX11
  void set_tuser(::std::string&& value);
  #endif
  void set_tuser(const char* value);
  void set_tuser(const void* value, size_t size);
  ::std::string* mutable_tuser();
  ::std::string* release_tuser();
  void set_allocated_tuser(::std::string* tuser);

  // optional bytes tkeep = 5;
  bool has_tkeep() const;
  void clear_tkeep();
  static const int kTkeepFieldNumber = 5;
  const ::std::string& tkeep() const;
  void set_tkeep(const ::std::string& value);
  #if LANG_CXX11
  void set_tkeep(::std::string&& value);
  #endif
  void set_tkeep(const char* value);
  void set_tkeep(const void* value, size_t size);
  ::std::string* mutable_tkeep();
  ::std::string* release_tkeep();
  void set_allocated_tkeep(::std::string* tkeep);

  // optional bytes tstrb = 6;
  bool has_tstrb() const;
  void clear_tstrb();
  static const int kTstrbFieldNumber = 6;
  const ::std::string& tstrb() const;
  void set_tstrb(const ::std::string& value);
  #if LANG_CXX11
  void set_tstrb(::std::string&& value);
  #endif
  void set_tstrb(const char* value);
  void set_tstrb(const void* value, size_t size);
  ::std::string* mutable_tstrb();
  ::std::string* release_tstrb();
  void set_allocated_tstrb(::std::string* tstrb);

  // required int32 data_length = 2;
  bool has_data_length() const;
  void clear_data_length();
  static const int kDataLengthFieldNumber = 2;
  ::X_GOOGLE_NAMESPACE::protobuf::int32 data_length() const;
  void set_data_length(::X_GOOGLE_NAMESPACE::protobuf::int32 value);

  // optional bool tlast = 3;
  bool has_tlast() const;
  void clear_tlast();
  static const int kTlastFieldNumber = 3;
  bool tlast() const;
  void set_tlast(bool value);

  // optional float delay = 7;
  bool has_delay() const;
  void clear_delay();
  static const int kDelayFieldNumber = 7;
  float delay() const;
  void set_delay(float value);

  // @@protoc_insertion_point(class_scope:xtlm_ipc.axi_stream_packet)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::X_GOOGLE_NAMESPACE::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::X_GOOGLE_NAMESPACE::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::X_GOOGLE_NAMESPACE::protobuf::internal::CachedSize _cached_size_;
  ::X_GOOGLE_NAMESPACE::protobuf::internal::ArenaStringPtr data_;
  ::X_GOOGLE_NAMESPACE::protobuf::internal::ArenaStringPtr tuser_;
  ::X_GOOGLE_NAMESPACE::protobuf::internal::ArenaStringPtr tkeep_;
  ::X_GOOGLE_NAMESPACE::protobuf::internal::ArenaStringPtr tstrb_;
  ::X_GOOGLE_NAMESPACE::protobuf::int32 data_length_;
  bool tlast_;
  float delay_;
  friend struct ::TableStruct_proto_2fxtlm_5fipc_5faxis_2eproto;
};
// -------------------------------------------------------------------

class axi_stream_resp :
    public ::X_GOOGLE_NAMESPACE::protobuf::Message /* @@protoc_insertion_point(class_definition:xtlm_ipc.axi_stream_resp) */ {
 public:
  axi_stream_resp();
  virtual ~axi_stream_resp();

  axi_stream_resp(const axi_stream_resp& from);

  inline axi_stream_resp& operator=(const axi_stream_resp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  axi_stream_resp(axi_stream_resp&& from) noexcept
    : axi_stream_resp() {
    *this = ::std::move(from);
  }

  inline axi_stream_resp& operator=(axi_stream_resp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::X_GOOGLE_NAMESPACE::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::X_GOOGLE_NAMESPACE::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::X_GOOGLE_NAMESPACE::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const axi_stream_resp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const axi_stream_resp* internal_default_instance() {
    return reinterpret_cast<const axi_stream_resp*>(
               &_axi_stream_resp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(axi_stream_resp* other);
  friend void swap(axi_stream_resp& a, axi_stream_resp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline axi_stream_resp* New() const final {
    return CreateMaybeMessage<axi_stream_resp>(nullptr);
  }

  axi_stream_resp* New(::X_GOOGLE_NAMESPACE::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<axi_stream_resp>(arena);
  }
  void CopyFrom(const ::X_GOOGLE_NAMESPACE::protobuf::Message& from) final;
  void MergeFrom(const ::X_GOOGLE_NAMESPACE::protobuf::Message& from) final;
  void CopyFrom(const axi_stream_resp& from);
  void MergeFrom(const axi_stream_resp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseContext* ctx);
  ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::X_GOOGLE_NAMESPACE::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::X_GOOGLE_NAMESPACE::protobuf::io::CodedOutputStream* output) const final;
  ::X_GOOGLE_NAMESPACE::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::X_GOOGLE_NAMESPACE::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(axi_stream_resp* other);
  private:
  inline ::X_GOOGLE_NAMESPACE::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::X_GOOGLE_NAMESPACE::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool ready = 1 [default = true];
  bool has_ready() const;
  void clear_ready();
  static const int kReadyFieldNumber = 1;
  bool ready() const;
  void set_ready(bool value);

  // @@protoc_insertion_point(class_scope:xtlm_ipc.axi_stream_resp)
 private:
  class HasBitSetters;

  ::X_GOOGLE_NAMESPACE::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::X_GOOGLE_NAMESPACE::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::X_GOOGLE_NAMESPACE::protobuf::internal::CachedSize _cached_size_;
  bool ready_;
  friend struct ::TableStruct_proto_2fxtlm_5fipc_5faxis_2eproto;
};
// -------------------------------------------------------------------

class axi_stream_responses :
    public ::X_GOOGLE_NAMESPACE::protobuf::Message /* @@protoc_insertion_point(class_definition:xtlm_ipc.axi_stream_responses) */ {
 public:
  axi_stream_responses();
  virtual ~axi_stream_responses();

  axi_stream_responses(const axi_stream_responses& from);

  inline axi_stream_responses& operator=(const axi_stream_responses& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  axi_stream_responses(axi_stream_responses&& from) noexcept
    : axi_stream_responses() {
    *this = ::std::move(from);
  }

  inline axi_stream_responses& operator=(axi_stream_responses&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::X_GOOGLE_NAMESPACE::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::X_GOOGLE_NAMESPACE::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::X_GOOGLE_NAMESPACE::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const axi_stream_responses& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const axi_stream_responses* internal_default_instance() {
    return reinterpret_cast<const axi_stream_responses*>(
               &_axi_stream_responses_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(axi_stream_responses* other);
  friend void swap(axi_stream_responses& a, axi_stream_responses& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline axi_stream_responses* New() const final {
    return CreateMaybeMessage<axi_stream_responses>(nullptr);
  }

  axi_stream_responses* New(::X_GOOGLE_NAMESPACE::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<axi_stream_responses>(arena);
  }
  void CopyFrom(const ::X_GOOGLE_NAMESPACE::protobuf::Message& from) final;
  void MergeFrom(const ::X_GOOGLE_NAMESPACE::protobuf::Message& from) final;
  void CopyFrom(const axi_stream_responses& from);
  void MergeFrom(const axi_stream_responses& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseContext* ctx);
  ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::X_GOOGLE_NAMESPACE::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::X_GOOGLE_NAMESPACE::protobuf::io::CodedOutputStream* output) const final;
  ::X_GOOGLE_NAMESPACE::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::X_GOOGLE_NAMESPACE::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(axi_stream_responses* other);
  private:
  inline ::X_GOOGLE_NAMESPACE::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::X_GOOGLE_NAMESPACE::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bool ready = 1 [packed = true];
  int ready_size() const;
  void clear_ready();
  static const int kReadyFieldNumber = 1;
  bool ready(int index) const;
  void set_ready(int index, bool value);
  void add_ready(bool value);
  const ::X_GOOGLE_NAMESPACE::protobuf::RepeatedField< bool >&
      ready() const;
  ::X_GOOGLE_NAMESPACE::protobuf::RepeatedField< bool >*
      mutable_ready();

  // @@protoc_insertion_point(class_scope:xtlm_ipc.axi_stream_responses)
 private:
  class HasBitSetters;

  ::X_GOOGLE_NAMESPACE::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::X_GOOGLE_NAMESPACE::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::X_GOOGLE_NAMESPACE::protobuf::internal::CachedSize _cached_size_;
  ::X_GOOGLE_NAMESPACE::protobuf::RepeatedField< bool > ready_;
  mutable std::atomic<int> _ready_cached_byte_size_;
  friend struct ::TableStruct_proto_2fxtlm_5fipc_5faxis_2eproto;
};
// -------------------------------------------------------------------

class axi_stream_sample_req :
    public ::X_GOOGLE_NAMESPACE::protobuf::Message /* @@protoc_insertion_point(class_definition:xtlm_ipc.axi_stream_sample_req) */ {
 public:
  axi_stream_sample_req();
  virtual ~axi_stream_sample_req();

  axi_stream_sample_req(const axi_stream_sample_req& from);

  inline axi_stream_sample_req& operator=(const axi_stream_sample_req& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  axi_stream_sample_req(axi_stream_sample_req&& from) noexcept
    : axi_stream_sample_req() {
    *this = ::std::move(from);
  }

  inline axi_stream_sample_req& operator=(axi_stream_sample_req&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::X_GOOGLE_NAMESPACE::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::X_GOOGLE_NAMESPACE::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::X_GOOGLE_NAMESPACE::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const axi_stream_sample_req& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const axi_stream_sample_req* internal_default_instance() {
    return reinterpret_cast<const axi_stream_sample_req*>(
               &_axi_stream_sample_req_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(axi_stream_sample_req* other);
  friend void swap(axi_stream_sample_req& a, axi_stream_sample_req& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline axi_stream_sample_req* New() const final {
    return CreateMaybeMessage<axi_stream_sample_req>(nullptr);
  }

  axi_stream_sample_req* New(::X_GOOGLE_NAMESPACE::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<axi_stream_sample_req>(arena);
  }
  void CopyFrom(const ::X_GOOGLE_NAMESPACE::protobuf::Message& from) final;
  void MergeFrom(const ::X_GOOGLE_NAMESPACE::protobuf::Message& from) final;
  void CopyFrom(const axi_stream_sample_req& from);
  void MergeFrom(const axi_stream_sample_req& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseContext* ctx);
  ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::X_GOOGLE_NAMESPACE::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::X_GOOGLE_NAMESPACE::protobuf::io::CodedOutputStream* output) const final;
  ::X_GOOGLE_NAMESPACE::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::X_GOOGLE_NAMESPACE::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(axi_stream_sample_req* other);
  private:
  inline ::X_GOOGLE_NAMESPACE::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::X_GOOGLE_NAMESPACE::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool sample = 1 [default = true];
  bool has_sample() const;
  void clear_sample();
  static const int kSampleFieldNumber = 1;
  bool sample() const;
  void set_sample(bool value);

  // @@protoc_insertion_point(class_scope:xtlm_ipc.axi_stream_sample_req)
 private:
  class HasBitSetters;

  ::X_GOOGLE_NAMESPACE::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::X_GOOGLE_NAMESPACE::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::X_GOOGLE_NAMESPACE::protobuf::internal::CachedSize _cached_size_;
  bool sample_;
  friend struct ::TableStruct_proto_2fxtlm_5fipc_5faxis_2eproto;
};
// -------------------------------------------------------------------

class axi_stream_frame :
    public ::X_GOOGLE_NAMESPACE::protobuf::Message /* @@protoc_insertion_point(class_definition:xtlm_ipc.axi_stream_frame) */ {
 public:
  axi_stream_frame();
  virtual ~axi_stream_frame();

  axi_stream_frame(const axi_stream_frame& from);

  inline axi_stream_frame& operator=(const axi_stream_frame& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  axi_stream_frame(axi_stream_frame&& from) noexcept
    : axi_stream_frame() {
    *this = ::std::move(from);
  }

  inline axi_stream_frame& operator=(axi_stream_frame&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::X_GOOGLE_NAMESPACE::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::X_GOOGLE_NAMESPACE::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::X_GOOGLE_NAMESPACE::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const axi_stream_frame& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const axi_stream_frame* internal_default_instance() {
    return reinterpret_cast<const axi_stream_frame*>(
               &_axi_stream_frame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(axi_stream_frame* other);
  friend void swap(axi_stream_frame& a, axi_stream_frame& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline axi_stream_frame* New() const final {
    return CreateMaybeMessage<axi_stream_frame>(nullptr);
  }

  axi_stream_frame* New(::X_GOOGLE_NAMESPACE::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<axi_stream_frame>(arena);
  }
  void CopyFrom(const ::X_GOOGLE_NAMESPACE::protobuf::Message& from) final;
  void MergeFrom(const ::X_GOOGLE_NAMESPACE::protobuf::Message& from) final;
  void CopyFrom(const axi_stream_frame& from);
  void MergeFrom(const axi_stream_frame& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseContext* ctx);
  ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::X_GOOGLE_NAMESPACE::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::X_GOOGLE_NAMESPACE::protobuf::io::CodedOutputStream* output) const final;
  ::X_GOOGLE_NAMESPACE::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::X_GOOGLE_NAMESPACE::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(axi_stream_frame* other);
  private:
  inline ::X_GOOGLE_NAMESPACE::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::X_GOOGLE_NAMESPACE::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .xtlm_ipc.axi_stream_packet frame = 1;
  int frame_size() const;
  void clear_frame();
  static const int kFrameFieldNumber = 1;
  ::xtlm_ipc::axi_stream_packet* mutable_frame(int index);
  ::X_GOOGLE_NAMESPACE::protobuf::RepeatedPtrField< ::xtlm_ipc::axi_stream_packet >*
      mutable_frame();
  const ::xtlm_ipc::axi_stream_packet& frame(int index) const;
  ::xtlm_ipc::axi_stream_packet* add_frame();
  const ::X_GOOGLE_NAMESPACE::protobuf::RepeatedPtrField< ::xtlm_ipc::axi_stream_packet >&
      frame() const;

  // @@protoc_insertion_point(class_scope:xtlm_ipc.axi_stream_frame)
 private:
  class HasBitSetters;

  ::X_GOOGLE_NAMESPACE::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::X_GOOGLE_NAMESPACE::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::X_GOOGLE_NAMESPACE::protobuf::internal::CachedSize _cached_size_;
  ::X_GOOGLE_NAMESPACE::protobuf::RepeatedPtrField< ::xtlm_ipc::axi_stream_packet > frame_;
  friend struct ::TableStruct_proto_2fxtlm_5fipc_5faxis_2eproto;
};
// -------------------------------------------------------------------

class axi_stream_frames :
    public ::X_GOOGLE_NAMESPACE::protobuf::Message /* @@protoc_insertion_point(class_definition:xtlm_ipc.axi_stream_frames) */ {
 public:
  axi_stream_frames();
  virtual ~axi_stream_frames();

  axi_stream_frames(const axi_stream_frames& from);

  inline axi_stream_frames& operator=(const axi_stream_frames& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  axi_stream_frames(axi_stream_frames&& from) noexcept
    : axi_stream_frames() {
    *this = ::std::move(from);
  }

  inline axi_stream_frames& operator=(axi_stream_frames&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::X_GOOGLE_NAMESPACE::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::X_GOOGLE_NAMESPACE::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::X_GOOGLE_NAMESPACE::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const axi_stream_frames& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const axi_stream_frames* internal_default_instance() {
    return reinterpret_cast<const axi_stream_frames*>(
               &_axi_stream_frames_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(axi_stream_frames* other);
  friend void swap(axi_stream_frames& a, axi_stream_frames& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline axi_stream_frames* New() const final {
    return CreateMaybeMessage<axi_stream_frames>(nullptr);
  }

  axi_stream_frames* New(::X_GOOGLE_NAMESPACE::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<axi_stream_frames>(arena);
  }
  void CopyFrom(const ::X_GOOGLE_NAMESPACE::protobuf::Message& from) final;
  void MergeFrom(const ::X_GOOGLE_NAMESPACE::protobuf::Message& from) final;
  void CopyFrom(const axi_stream_frames& from);
  void MergeFrom(const axi_stream_frames& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseContext* ctx);
  ::X_GOOGLE_NAMESPACE::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::X_GOOGLE_NAMESPACE::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::X_GOOGLE_NAMESPACE::protobuf::io::CodedOutputStream* output) const final;
  ::X_GOOGLE_NAMESPACE::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::X_GOOGLE_NAMESPACE::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(axi_stream_frames* other);
  private:
  inline ::X_GOOGLE_NAMESPACE::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::X_GOOGLE_NAMESPACE::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .xtlm_ipc.axi_stream_frame frames = 1;
  int frames_size() const;
  void clear_frames();
  static const int kFramesFieldNumber = 1;
  ::xtlm_ipc::axi_stream_frame* mutable_frames(int index);
  ::X_GOOGLE_NAMESPACE::protobuf::RepeatedPtrField< ::xtlm_ipc::axi_stream_frame >*
      mutable_frames();
  const ::xtlm_ipc::axi_stream_frame& frames(int index) const;
  ::xtlm_ipc::axi_stream_frame* add_frames();
  const ::X_GOOGLE_NAMESPACE::protobuf::RepeatedPtrField< ::xtlm_ipc::axi_stream_frame >&
      frames() const;

  // @@protoc_insertion_point(class_scope:xtlm_ipc.axi_stream_frames)
 private:
  class HasBitSetters;

  ::X_GOOGLE_NAMESPACE::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::X_GOOGLE_NAMESPACE::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::X_GOOGLE_NAMESPACE::protobuf::internal::CachedSize _cached_size_;
  ::X_GOOGLE_NAMESPACE::protobuf::RepeatedPtrField< ::xtlm_ipc::axi_stream_frame > frames_;
  friend struct ::TableStruct_proto_2fxtlm_5fipc_5faxis_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// axi_stream_packet

// required bytes data = 1;
inline bool axi_stream_packet::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void axi_stream_packet::clear_data() {
  data_.ClearToEmptyNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& axi_stream_packet::data() const {
  // @@protoc_insertion_point(field_get:xtlm_ipc.axi_stream_packet.data)
  return data_.GetNoArena();
}
inline void axi_stream_packet::set_data(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  data_.SetNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:xtlm_ipc.axi_stream_packet.data)
}
#if LANG_CXX11
inline void axi_stream_packet::set_data(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  data_.SetNoArena(
    &::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:xtlm_ipc.axi_stream_packet.data)
}
#endif
inline void axi_stream_packet::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  data_.SetNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:xtlm_ipc.axi_stream_packet.data)
}
inline void axi_stream_packet::set_data(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  data_.SetNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:xtlm_ipc.axi_stream_packet.data)
}
inline ::std::string* axi_stream_packet::mutable_data() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:xtlm_ipc.axi_stream_packet.data)
  return data_.MutableNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* axi_stream_packet::release_data() {
  // @@protoc_insertion_point(field_release:xtlm_ipc.axi_stream_packet.data)
  if (!has_data()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return data_.ReleaseNonDefaultNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void axi_stream_packet::set_allocated_data(::std::string* data) {
  if (data != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  data_.SetAllocatedNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:xtlm_ipc.axi_stream_packet.data)
}

// required int32 data_length = 2;
inline bool axi_stream_packet::has_data_length() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void axi_stream_packet::clear_data_length() {
  data_length_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::X_GOOGLE_NAMESPACE::protobuf::int32 axi_stream_packet::data_length() const {
  // @@protoc_insertion_point(field_get:xtlm_ipc.axi_stream_packet.data_length)
  return data_length_;
}
inline void axi_stream_packet::set_data_length(::X_GOOGLE_NAMESPACE::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000010u;
  data_length_ = value;
  // @@protoc_insertion_point(field_set:xtlm_ipc.axi_stream_packet.data_length)
}

// optional bool tlast = 3;
inline bool axi_stream_packet::has_tlast() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void axi_stream_packet::clear_tlast() {
  tlast_ = false;
  _has_bits_[0] &= ~0x00000020u;
}
inline bool axi_stream_packet::tlast() const {
  // @@protoc_insertion_point(field_get:xtlm_ipc.axi_stream_packet.tlast)
  return tlast_;
}
inline void axi_stream_packet::set_tlast(bool value) {
  _has_bits_[0] |= 0x00000020u;
  tlast_ = value;
  // @@protoc_insertion_point(field_set:xtlm_ipc.axi_stream_packet.tlast)
}

// optional bytes tuser = 4;
inline bool axi_stream_packet::has_tuser() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void axi_stream_packet::clear_tuser() {
  tuser_.ClearToEmptyNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& axi_stream_packet::tuser() const {
  // @@protoc_insertion_point(field_get:xtlm_ipc.axi_stream_packet.tuser)
  return tuser_.GetNoArena();
}
inline void axi_stream_packet::set_tuser(const ::std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  tuser_.SetNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:xtlm_ipc.axi_stream_packet.tuser)
}
#if LANG_CXX11
inline void axi_stream_packet::set_tuser(::std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  tuser_.SetNoArena(
    &::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:xtlm_ipc.axi_stream_packet.tuser)
}
#endif
inline void axi_stream_packet::set_tuser(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  tuser_.SetNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:xtlm_ipc.axi_stream_packet.tuser)
}
inline void axi_stream_packet::set_tuser(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  tuser_.SetNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:xtlm_ipc.axi_stream_packet.tuser)
}
inline ::std::string* axi_stream_packet::mutable_tuser() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:xtlm_ipc.axi_stream_packet.tuser)
  return tuser_.MutableNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* axi_stream_packet::release_tuser() {
  // @@protoc_insertion_point(field_release:xtlm_ipc.axi_stream_packet.tuser)
  if (!has_tuser()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return tuser_.ReleaseNonDefaultNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void axi_stream_packet::set_allocated_tuser(::std::string* tuser) {
  if (tuser != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  tuser_.SetAllocatedNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), tuser);
  // @@protoc_insertion_point(field_set_allocated:xtlm_ipc.axi_stream_packet.tuser)
}

// optional bytes tkeep = 5;
inline bool axi_stream_packet::has_tkeep() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void axi_stream_packet::clear_tkeep() {
  tkeep_.ClearToEmptyNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::std::string& axi_stream_packet::tkeep() const {
  // @@protoc_insertion_point(field_get:xtlm_ipc.axi_stream_packet.tkeep)
  return tkeep_.GetNoArena();
}
inline void axi_stream_packet::set_tkeep(const ::std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  tkeep_.SetNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:xtlm_ipc.axi_stream_packet.tkeep)
}
#if LANG_CXX11
inline void axi_stream_packet::set_tkeep(::std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  tkeep_.SetNoArena(
    &::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:xtlm_ipc.axi_stream_packet.tkeep)
}
#endif
inline void axi_stream_packet::set_tkeep(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  tkeep_.SetNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:xtlm_ipc.axi_stream_packet.tkeep)
}
inline void axi_stream_packet::set_tkeep(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000004u;
  tkeep_.SetNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:xtlm_ipc.axi_stream_packet.tkeep)
}
inline ::std::string* axi_stream_packet::mutable_tkeep() {
  _has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_mutable:xtlm_ipc.axi_stream_packet.tkeep)
  return tkeep_.MutableNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* axi_stream_packet::release_tkeep() {
  // @@protoc_insertion_point(field_release:xtlm_ipc.axi_stream_packet.tkeep)
  if (!has_tkeep()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return tkeep_.ReleaseNonDefaultNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void axi_stream_packet::set_allocated_tkeep(::std::string* tkeep) {
  if (tkeep != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  tkeep_.SetAllocatedNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), tkeep);
  // @@protoc_insertion_point(field_set_allocated:xtlm_ipc.axi_stream_packet.tkeep)
}

// optional bytes tstrb = 6;
inline bool axi_stream_packet::has_tstrb() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void axi_stream_packet::clear_tstrb() {
  tstrb_.ClearToEmptyNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000008u;
}
inline const ::std::string& axi_stream_packet::tstrb() const {
  // @@protoc_insertion_point(field_get:xtlm_ipc.axi_stream_packet.tstrb)
  return tstrb_.GetNoArena();
}
inline void axi_stream_packet::set_tstrb(const ::std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  tstrb_.SetNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:xtlm_ipc.axi_stream_packet.tstrb)
}
#if LANG_CXX11
inline void axi_stream_packet::set_tstrb(::std::string&& value) {
  _has_bits_[0] |= 0x00000008u;
  tstrb_.SetNoArena(
    &::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:xtlm_ipc.axi_stream_packet.tstrb)
}
#endif
inline void axi_stream_packet::set_tstrb(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000008u;
  tstrb_.SetNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:xtlm_ipc.axi_stream_packet.tstrb)
}
inline void axi_stream_packet::set_tstrb(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000008u;
  tstrb_.SetNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:xtlm_ipc.axi_stream_packet.tstrb)
}
inline ::std::string* axi_stream_packet::mutable_tstrb() {
  _has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_mutable:xtlm_ipc.axi_stream_packet.tstrb)
  return tstrb_.MutableNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* axi_stream_packet::release_tstrb() {
  // @@protoc_insertion_point(field_release:xtlm_ipc.axi_stream_packet.tstrb)
  if (!has_tstrb()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  return tstrb_.ReleaseNonDefaultNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void axi_stream_packet::set_allocated_tstrb(::std::string* tstrb) {
  if (tstrb != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  tstrb_.SetAllocatedNoArena(&::X_GOOGLE_NAMESPACE::protobuf::internal::GetEmptyStringAlreadyInited(), tstrb);
  // @@protoc_insertion_point(field_set_allocated:xtlm_ipc.axi_stream_packet.tstrb)
}

// optional float delay = 7;
inline bool axi_stream_packet::has_delay() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void axi_stream_packet::clear_delay() {
  delay_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline float axi_stream_packet::delay() const {
  // @@protoc_insertion_point(field_get:xtlm_ipc.axi_stream_packet.delay)
  return delay_;
}
inline void axi_stream_packet::set_delay(float value) {
  _has_bits_[0] |= 0x00000040u;
  delay_ = value;
  // @@protoc_insertion_point(field_set:xtlm_ipc.axi_stream_packet.delay)
}

// -------------------------------------------------------------------

// axi_stream_resp

// optional bool ready = 1 [default = true];
inline bool axi_stream_resp::has_ready() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void axi_stream_resp::clear_ready() {
  ready_ = true;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool axi_stream_resp::ready() const {
  // @@protoc_insertion_point(field_get:xtlm_ipc.axi_stream_resp.ready)
  return ready_;
}
inline void axi_stream_resp::set_ready(bool value) {
  _has_bits_[0] |= 0x00000001u;
  ready_ = value;
  // @@protoc_insertion_point(field_set:xtlm_ipc.axi_stream_resp.ready)
}

// -------------------------------------------------------------------

// axi_stream_responses

// repeated bool ready = 1 [packed = true];
inline int axi_stream_responses::ready_size() const {
  return ready_.size();
}
inline void axi_stream_responses::clear_ready() {
  ready_.Clear();
}
inline bool axi_stream_responses::ready(int index) const {
  // @@protoc_insertion_point(field_get:xtlm_ipc.axi_stream_responses.ready)
  return ready_.Get(index);
}
inline void axi_stream_responses::set_ready(int index, bool value) {
  ready_.Set(index, value);
  // @@protoc_insertion_point(field_set:xtlm_ipc.axi_stream_responses.ready)
}
inline void axi_stream_responses::add_ready(bool value) {
  ready_.Add(value);
  // @@protoc_insertion_point(field_add:xtlm_ipc.axi_stream_responses.ready)
}
inline const ::X_GOOGLE_NAMESPACE::protobuf::RepeatedField< bool >&
axi_stream_responses::ready() const {
  // @@protoc_insertion_point(field_list:xtlm_ipc.axi_stream_responses.ready)
  return ready_;
}
inline ::X_GOOGLE_NAMESPACE::protobuf::RepeatedField< bool >*
axi_stream_responses::mutable_ready() {
  // @@protoc_insertion_point(field_mutable_list:xtlm_ipc.axi_stream_responses.ready)
  return &ready_;
}

// -------------------------------------------------------------------

// axi_stream_sample_req

// optional bool sample = 1 [default = true];
inline bool axi_stream_sample_req::has_sample() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void axi_stream_sample_req::clear_sample() {
  sample_ = true;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool axi_stream_sample_req::sample() const {
  // @@protoc_insertion_point(field_get:xtlm_ipc.axi_stream_sample_req.sample)
  return sample_;
}
inline void axi_stream_sample_req::set_sample(bool value) {
  _has_bits_[0] |= 0x00000001u;
  sample_ = value;
  // @@protoc_insertion_point(field_set:xtlm_ipc.axi_stream_sample_req.sample)
}

// -------------------------------------------------------------------

// axi_stream_frame

// repeated .xtlm_ipc.axi_stream_packet frame = 1;
inline int axi_stream_frame::frame_size() const {
  return frame_.size();
}
inline void axi_stream_frame::clear_frame() {
  frame_.Clear();
}
inline ::xtlm_ipc::axi_stream_packet* axi_stream_frame::mutable_frame(int index) {
  // @@protoc_insertion_point(field_mutable:xtlm_ipc.axi_stream_frame.frame)
  return frame_.Mutable(index);
}
inline ::X_GOOGLE_NAMESPACE::protobuf::RepeatedPtrField< ::xtlm_ipc::axi_stream_packet >*
axi_stream_frame::mutable_frame() {
  // @@protoc_insertion_point(field_mutable_list:xtlm_ipc.axi_stream_frame.frame)
  return &frame_;
}
inline const ::xtlm_ipc::axi_stream_packet& axi_stream_frame::frame(int index) const {
  // @@protoc_insertion_point(field_get:xtlm_ipc.axi_stream_frame.frame)
  return frame_.Get(index);
}
inline ::xtlm_ipc::axi_stream_packet* axi_stream_frame::add_frame() {
  // @@protoc_insertion_point(field_add:xtlm_ipc.axi_stream_frame.frame)
  return frame_.Add();
}
inline const ::X_GOOGLE_NAMESPACE::protobuf::RepeatedPtrField< ::xtlm_ipc::axi_stream_packet >&
axi_stream_frame::frame() const {
  // @@protoc_insertion_point(field_list:xtlm_ipc.axi_stream_frame.frame)
  return frame_;
}

// -------------------------------------------------------------------

// axi_stream_frames

// repeated .xtlm_ipc.axi_stream_frame frames = 1;
inline int axi_stream_frames::frames_size() const {
  return frames_.size();
}
inline void axi_stream_frames::clear_frames() {
  frames_.Clear();
}
inline ::xtlm_ipc::axi_stream_frame* axi_stream_frames::mutable_frames(int index) {
  // @@protoc_insertion_point(field_mutable:xtlm_ipc.axi_stream_frames.frames)
  return frames_.Mutable(index);
}
inline ::X_GOOGLE_NAMESPACE::protobuf::RepeatedPtrField< ::xtlm_ipc::axi_stream_frame >*
axi_stream_frames::mutable_frames() {
  // @@protoc_insertion_point(field_mutable_list:xtlm_ipc.axi_stream_frames.frames)
  return &frames_;
}
inline const ::xtlm_ipc::axi_stream_frame& axi_stream_frames::frames(int index) const {
  // @@protoc_insertion_point(field_get:xtlm_ipc.axi_stream_frames.frames)
  return frames_.Get(index);
}
inline ::xtlm_ipc::axi_stream_frame* axi_stream_frames::add_frames() {
  // @@protoc_insertion_point(field_add:xtlm_ipc.axi_stream_frames.frames)
  return frames_.Add();
}
inline const ::X_GOOGLE_NAMESPACE::protobuf::RepeatedPtrField< ::xtlm_ipc::axi_stream_frame >&
axi_stream_frames::frames() const {
  // @@protoc_insertion_point(field_list:xtlm_ipc.axi_stream_frames.frames)
  return frames_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace xtlm_ipc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_proto_2fxtlm_5fipc_5faxis_2eproto
