# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /Volumes/export/isn/soumil/Xilinx/ifat6/pcb_ok_xem7310/pcb_ok_xem7310.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
# IP: The module: 'fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /Volumes/export/isn/soumil/Xilinx/ifat6/pcb_ok_xem7310/pcb_ok_xem7310.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /Volumes/export/isn/soumil/Xilinx/ifat6/pcb_ok_xem7310/pcb_ok_xem7310.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /Volumes/export/isn/soumil/Xilinx/ifat6/pcb_ok_xem7310/pcb_ok_xem7310.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
# IP: The module: 'fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /Volumes/export/isn/soumil/Xilinx/ifat6/pcb_ok_xem7310/pcb_ok_xem7310.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /Volumes/export/isn/soumil/Xilinx/ifat6/pcb_ok_xem7310/pcb_ok_xem7310.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
