# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /Volumes/export/isn/soumil/Xilinx/ifat6/pcb_ok_xem7310/ifat6_XEM7310-A200.xdc

# IP: ip/clk_wiz_1/clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet
