# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Soumil/OneDrive - UC San Diego/research/IFAT6_PCB/Verilog/IFAT6_PCB/IFAT6_PCB.srcs/sources_1/ip/frontpanel_IFAT6_1/frontpanel_IFAT6.xci
# IP: The module: 'frontpanel_IFAT6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Soumil/OneDrive - UC San Diego/research/IFAT6_PCB/Verilog/IFAT6_PCB/IFAT6_PCB.gen/sources_1/ip/frontpanel_IFAT6_1/frontpanel_IFAT6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'frontpanel_IFAT6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Soumil/OneDrive - UC San Diego/research/IFAT6_PCB/Verilog/IFAT6_PCB/IFAT6_PCB.gen/sources_1/ip/frontpanel_IFAT6_1/gateware/synthesis/xem7310.xdc
# XDC: The top module name and the constraint reference have the same name: 'frontpanel_IFAT6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Soumil/OneDrive - UC San Diego/research/IFAT6_PCB/Verilog/IFAT6_PCB/IFAT6_PCB.srcs/sources_1/ip/frontpanel_IFAT6_1/frontpanel_IFAT6.xci
# IP: The module: 'frontpanel_IFAT6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Soumil/OneDrive - UC San Diego/research/IFAT6_PCB/Verilog/IFAT6_PCB/IFAT6_PCB.gen/sources_1/ip/frontpanel_IFAT6_1/frontpanel_IFAT6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'frontpanel_IFAT6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Soumil/OneDrive - UC San Diego/research/IFAT6_PCB/Verilog/IFAT6_PCB/IFAT6_PCB.gen/sources_1/ip/frontpanel_IFAT6_1/gateware/synthesis/xem7310.xdc
# XDC: The top module name and the constraint reference have the same name: 'frontpanel_IFAT6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
