#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Cadence Xcelium Parallel Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Mon Oct 03 16:11:29 PDT 2022
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: compile.sh
#
# ****************************************************************************
# delete log files (if exist)
reset_log()
{
logs=(compile.log xmvhdl.log xmvlog.log xmsc.log .tmp_log)
for (( i=0; i<${#logs[*]}; i++ )); do
  file="${logs[i]}"
  if [[ -e $file ]]; then
    rm -rf $file
  fi
done
}
reset_log
set -Eeuo pipefail

# installation path setting
bin_path="/cad/installs/XCELIUM2103//tools.lnx86/bin"

# directory path for design sources and include directories (if any) wrt this path
origin_dir="."

# set xmvlog command line args
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# compile design source files
$bin_path/xmvlog $xmvlog_opts -work xil_defaultlib  +incdir+"$origin_dir/../../../../pcb_ok_xem7310.gen/sources_1/ip/frontpanel_0/gateware/common" +incdir+"$origin_dir/../../../../pcb_ok_xem7310.gen/sources_1/ip/frontpanel_0/gateware/simulation/FrontPanel" \
"$origin_dir/../../../../pcb_ok_xem7310.gen/sources_1/ip/frontpanel_0/gateware/simulation/frontpanel_0_wrapper_simulation.v" \
"$origin_dir/../../../../pcb_ok_xem7310.gen/sources_1/ip/frontpanel_0/gateware/simulation/FrontPanel/okHost.v" \
"$origin_dir/../../../../pcb_ok_xem7310.gen/sources_1/ip/frontpanel_0/gateware/simulation/FrontPanel/okWireOR.v" \
"$origin_dir/../../../../pcb_ok_xem7310.gen/sources_1/ip/frontpanel_0/gateware/simulation/FrontPanel/okWireIn.v" \
"$origin_dir/../../../../pcb_ok_xem7310.gen/sources_1/ip/frontpanel_0/gateware/simulation/FrontPanel/okWireOut.v" \
"$origin_dir/../../../../pcb_ok_xem7310.gen/sources_1/ip/frontpanel_0/gateware/simulation/frontpanel_0_simulation.v" \
"$origin_dir/../../../../pcb_ok_xem7310.srcs/sim_1/new/top_tb.v" \
2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

# compile glbl module
$bin_path/xmvlog $xmvlog_opts -work xil_defaultlib "glbl.v" \
2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
