#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Cadence Xcelium Parallel Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Oct 03 16:11:29 PDT 2022
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# installation path setting
bin_path="/cad/installs/XCELIUM2103//tools.lnx86/bin"

# set xmelab command line args
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set design libraries
design_libs_elab="-libname xil_defaultlib -libname unisims_ver -libname unimacro_ver -libname secureip -libname xpm"

# run elaboration
$bin_path/xmelab $xmelab_opts $design_libs_elab xil_defaultlib.top_tb xil_defaultlib.glbl
